name: publish-docker-master
on:
  push:
    branches:
      - main

jobs:
  build_publish:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: TRUE
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0

      # Build and test Docker image
      - run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u nanocurrency --password-stdin
          docker pull ghcr.io/nanocurrency/mkdocs-material-insiders:latest
          docker build -t ghcr.io/nanocurrency/nano-docs:latest .
          docker push ghcr.io/nanocurrency/nano-docs:latest
